### ISSUE TITLE
array in url a[]=1&a[]=2&a[]=3

### ISSUE THREAD

**Issue by Venzon** [Mikhus/jsurl#10]
Is it possible to create url like this: a[]=1&a[]=2&a[]=3 ?

regards

**Comment by jakobjp** [comment]
You can change line 189 from
`s += e( i) + '=' + e( this[i][ii]);`
to 
`s += e( i) + '[]=' + e( this[i][ii]);`
which will make the url structure you ask for, and is needed for instance when parsing the request with PHP GET params.

**Comment by webadequate** [comment]
Thank You!

**Comment by briedis** [comment]
This feature would be awesome!

PS. Love this library, really nice and easy to use

**Comment by webadequate** [comment]
I just did it:

    public static function getArrayFromVar( $url, $nameVar)
    {
      if(!empty($url))
      {
        $query  = explode('&', $url);
        $params = [];
  
        foreach( $query as $param )
        {
          list($name, $value) = explode('=', $param, 2);
  
          if( empty( $value ) )
          {
            continue;
          }
          $params[urldecode($name)][] = urldecode($value);
        }
  
        return isset($params[$nameVar]) ? $params[$nameVar] : NULL;
      }
      else
      {
        return NULL;
      }
    }

**Comment by briedis** [comment]
I don't know how this helps, because it's PHP :)

**Comment by Mikhus** [comment]
I'd prefer to keep this library generic, and do not have any clue why it should be PHP-specific. It is a problem of PHP's $GET. There are plenty other tools which people can use this library in cooperation (Python, NodeJS, ruby, etc) and none of them expects PHP-like style of parsing query string.

**Comment by Mikhus** [comment]
Related: #5
