### ISSUE TITLE
Consider adding tags for the repo.

### ISSUE THREAD

**Issue by Piicksarn** [Mikhus/jsurl#17]
Hi @Mikhus 

Your great work had been recommend being added in  [CDNJS](https://github.com/cdnjs/cdnjs).
However, we need tags for repo to specify points in history and mark release points.
It's helpful for users to know the version and status of repository, and would enable wider distribution of the library.
Would you please consider on using tags?

Thank you!
Piicksarn
[#6428](https://github.com/cdnjs/cdnjs/issues/6428)

**Comment by Mikhus** [comment]
Hi. Thank you for your consideration. Please, provide me a bit more details. Which tags you mean? Git repo tags? Do I understand correctly?

**Comment by Piicksarn** [comment]
@Mikhus, yes!
We are talking about git repo tags :smiley: 
Thank you!

**Comment by Mikhus** [comment]
@Piicksarn,
Some meaningful tags added, tell me if it is something enough for you.
All kind regards!

**Comment by Piicksarn** [comment]
Thank you! 
[#7024](https://github.com/cdnjs/cdnjs/pull/7024)
