### ISSUE TITLE
Query param with name "count"

### ISSUE THREAD

**Issue by dreamagex** [Mikhus/jsurl#18]
Hi,

When parsing an url with a query param named "count", the name "count" collides with the method "count" of the Query object, and the parameter count is being discarded as a side effect of this.

See https://jsbin.com/vuyuyaxako/edit?html,js,output

**Comment by Mikhus** [comment]
Oops, nice trouble, thanks for the report, will take a look

**Comment by Mikhus** [comment]
This is fixed in version 2.0.0.
Thank you for contribution.
