### ISSUE TITLE
Bower: no versions available

### ISSUE THREAD

**Issue by AdamFrey** [Mikhus/jsurl#8]
Some tools that use Bower expect a package to have versions associated with it.  Bower can't find any versions for the jsurl package because there are no git tags pushed for this repo. See: 
![screen shot 2014-07-17 at 10 24 41 am](https://cloud.githubusercontent.com/assets/465987/3614165/2224a238-0dbe-11e4-8242-a192bed75a6c.png)

Please push a git tag for this project. See here for more information: http://stackoverflow.com/a/20055632

**Comment by AndrewEastwood** [comment]
@Mikhus please bump first version. set whatever you want just to be able manage version via bower

**Comment by gEndelf** [comment]
+1

**Comment by YuriSolovyov** [comment]
+1

**Comment by Mikhus** [comment]
Fixed with 1.2.3
